language: java

jdk: openjdk11

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
install:
  - mkdir .deps
  - cd .deps
  - wget https://ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip
  - unzip ghidra_9.1.2_PUBLIC_20200212.zip
  - rm ghidra_9.1.2_PUBLIC_20200212.zip
  - export GHIDRA_INSTALL_DIR=$PWD/ghidra_9.1.2_PUBLIC
  - cd ..

script:
  - gradle
  
deploy:
  provider: releases
  file_glob: true
  file: dist/*.zip
  skip_cleanup: true
  draft: true
  edge: true
